apiVersion: v1
kind: Secret
metadata:
  name: github-repo-acc
  namespace: dev-bookinfo

#  namespace: openshift-gitops  
#  namespace: preda-devops-istio-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
#  url: https://github.com/semirmussa1/ci-cd-istio-tekton_pvt
  url: https://github.com/AccenturePreda/dso-project-bookinfo
#  password: ${GITHUB_TOKEN}
  password: <password>
  username: not-used