kind: Secret
apiVersion: v1
metadata:
  name: dso-quay-user
  namespace: bookinfo
  annotations:
    tekton.dev/docker-0: >-
      https://dso-quay-registry-quay-quay-enterprise.apps.ocp1.azure.dso.digital.mod.uk
data:
  password: <password>
  username: <username>
type: kubernetes.io/basic-auth