{
 "title": "API Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "apiserver",
    "label": "apiserver",
    "query": "label_values(apiserver_request_total, apiserver)"
   },
   { "name": "period", "label": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "API Request Duration by Verb - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"$apiserver\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$period])) by(verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "etcd Request Duration - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[$period])) by(operation,le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Request Duration by Resource and Verb - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"$apiserver\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$period])) by(resource,verb,le)))",
     "legendFormat": "{{resource}}-{{verb}}"
    }
   ]
  },
  {
   "title": "Request Rate by Resource and Verb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(apiserver_request_total{apiserver=\"$apiserver\"}[$period])) by(resource,verb))",
     "legendFormat": "{{resource}}-{{verb}}"
    }
   ]
  },
  {
   "title": "Request Duration by Read vs Write - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"$apiserver\",verb=~\"LIST|GET\"}[$period])) by(le))",
     "legendFormat": "read"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"$apiserver\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[$period])) by(le))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Request Rate by Read vs Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",verb=~\"LIST|GET\"}[$period]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[$period]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Requests Dropped Rate",
   "type": "graph",
   "description": "Number of requests dropped with 'Try again later' response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_dropped_requests_total{apiserver=\"$apiserver\"}[$period])) by (request_kind)",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  {
   "title": "Requests Terminated Rate",
   "type": "graph",
   "description": "Number of requests which apiserver terminated in self-defense.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{apiserver=\"$apiserver\"}[$period])) by(component,resource)",
     "legendFormat": "{{component}}-{{resource}}"
    }
   ]
  },
  {
   "title": "Request Rate by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\"}[$period])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Rate by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\"}[$period])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Long Running Requests by Resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(apiserver_longrunning_gauge{apiserver=\"$apiserver\"}) by(resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Long Running Requests by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge{apiserver=\"$apiserver\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests in Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{apiserver=\"$apiserver\"}) by (instance,request_kind)",
     "legendFormat": "{{instance}}:{{request_kind}}"
    }
   ]
  },
  {
   "title": "Response Bytes per Second by Instance",
   "type": "graph",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_response_sizes_sum{apiserver=\"$apiserver\"}[$period])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Bytes per Second by Resource and Verb",
   "type": "graph",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(apiserver_response_sizes_sum{apiserver=\"$apiserver\"}[$period])) by(resource,verb))",
     "legendFormat": "{{resource}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Requests Rejected",
   "type": "graph",
   "description": "Number of requests rejected by API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_rejected_requests_total{apiserver=\"$apiserver\"}[$period])) by (flow_schema,priority_level,reason)",
     "legendFormat": "{{flow_schema}}:{{priority_level}}:{{reason}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Wait Duration - 99th Percentile",
   "type": "graph",
   "description": "Length of time a request spent waiting in its queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_wait_duration_seconds_bucket{apiserver=\"$apiserver\",execute=\"true\"}[$period])) by(flow_schema, priority_level, le))",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Queue Length",
   "type": "graph",
   "description": "Length of queue in the API Priority and Fairness system, as seen by each request after it is enqueued",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_queue_length_after_enqueue_bucket{apiserver=\"$apiserver\"}[$period])) by(flow_schema, priority_level, le))",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Dispatch Rate",
   "type": "graph",
   "description": "Number of requests released by API Priority and Fairness system for service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_dispatched_requests_total{apiserver=\"$apiserver\"}[$period])) by(flow_schema,priority_level)",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Execution Duration - 99th Percentile",
   "type": "graph",
   "description": "Duration of request execution in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_execution_seconds_bucket{apiserver=\"$apiserver\"}[$period])) by(flow_schema, priority_level, le)) ",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Currently Executing Requests",
   "type": "graph",
   "description": "Number of requests currently executing in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_executing_requests{apiserver=\"$apiserver\"}) by (flow_schema,priority_level)",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Concurrency Limit by Priority Level",
   "type": "graph",
   "description": "Shared concurrency limit in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_request_concurrency_limit{apiserver=\"$apiserver\"}) by (priority_level)",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Pending in Queue",
   "type": "graph",
   "description": "Number of requests currently pending in queues of the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_inqueue_requests{apiserver=\"$apiserver\"}) by (flow_schema,priority_level)",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Self-requests Rate by Resource and Verb",
   "type": "graph",
   "description": "Counter of apiserver self-requests broken out for each verb, API resource and subresource.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_selfrequest_total{apiserver=\"$apiserver\"}[$period])) by(resource,verb)",
     "legendFormat": "{{resource}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Requests Aborted Rate by Instance",
   "type": "graph",
   "description": "Number of requests which apiserver aborted possibly due to a timeout, for each group, version, verb, resource, subresource and scope",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_aborts_total{apiserver=\"$apiserver\"}[$period])) by(resource,verb)",
     "legendFormat": "{{resource}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Server Filter Duration - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, histogram_quantile(0.99, sum(rate(apiserver_request_filter_duration_seconds_bucket{apiserver=\"$apiserver\"}[$period])) by(filter,le)))",
     "legendFormat": "{{filter}}"
    }
   ]
  },
  {
   "title": "Rate of Events Sent to Watch Clients",
   "type": "graph",
   "description": "Number of events sent in watch clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, sum(rate(apiserver_watch_events_total{apiserver=\"$apiserver\"}[$period])) by(group,kind))",
     "legendFormat": "{{group}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Watch Event Size per Second by Group and Kind ",
   "type": "graph",
   "description": "Watch event size distribution in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(apiserver_watch_events_sizes_sum{apiserver=\"$apiserver\"}[$period])) by(group,kind))",
     "legendFormat": "{{group}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Registered Watchers",
   "type": "graph",
   "description": "Number of currently registered watchers for a given resources",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, sum(apiserver_registered_watchers{apiserver=\"$apiserver\"}) by(group,kind))",
     "legendFormat": "{{group}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of TLS Handshake Error",
   "type": "graph",
   "description": "Number of requests dropped with 'TLS handshake error from' error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_tls_handshake_errors_total{apiserver=\"$apiserver\"}[$period])) by()"
    }
   ]
  },
  {
   "title": "etcd Object Count",
   "type": "graph",
   "description": "Number of stored objects at the time of last check split by kind.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, max(etcd_object_counts) by (resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}