server {
    listen 8080;
    default_type application/json;

    location = /endpoints {
        alias /data/endpoints.json;
        add_header Access-Control-Allow-Origin "*";
        add_header Cache-Control no-cache;
    }

    location / {
        return 200 '{"message":"mock api - use /endpoints for data"}';
        add_header Content-Type application/json;
        add_header Access-Control-Allow-Origin "*";
    }
}
