server {
    listen 8080;
    default_type application/json;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy API calls to httpbin mock-api service
    location /endpoints {
        proxy_pass http://httpbin:8080/endpoints;
        proxy_set_header Host $host;
        add_header Cache-Control no-cache;
    }

    location /unitEndpoints {
        proxy_pass http://httpbin:8080/unitEndpoints;
        proxy_set_header Host $host;
        add_header Cache-Control no-cache;
    }

    # Static files
    location / {
        try_files $uri $uri/ /index.html;
    }
}
