apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acs-operator
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: "rhacs-3.74"
  installPlanApproval: Manual
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace