apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: 3scale-operatorgroup
  namespace: three-scale
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - three-scale