kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-l2-support-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: AZ-APP-OBP DevSecOps L2 Support
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit