kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-l1-support-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: AZ-APP-OBP DevSecOps L1 Support
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit