kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-cluster-viewer
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: AZ-APP-OBP Platform Development Cluster Viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
