apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-telemetry
  namespace: open-telemetry
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - open-telemetry