apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-oauth
  namespace: pgadmin
type: Opaque
data:
  CLIENT_ID: MDk5NzQ3MDQtODA2MS00OWFiLWJjOWMtMzgwYzM1ZmIzNTFk
  CLIENT_SECRET: QVg2OFF+bk9vMUtxbkx0ZGd4Mnl2UzNYLUNkZkt5S2ZBQUR4WWFoZQ==
  PASSWORD: dGVzdDEyMw==
  PGADMIN_DEFAULT_EMAIL: cy5zdW50aGFyYXZhZGl2dUB1ay5uYXRpb25hbGdyaWQuY29t
  TENANT_ID: Zjk4YTZhNTMtMjVmMy00MjEyLTkwMWMtYzc3ODdmY2QzNDk1