apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - role-binding-control-plane-ro.yaml
  - roles-mesh-view.yaml
  - group-mesh-ro.yaml
  - service-entry-kube-api-server.yaml
  - servicemeshcontrolplane.yaml