apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: istio-ctlplane-elasticsearch-01
  name: istio-ctlplane-elasticsearch-01
  annotations:
spec:
  version: v2.1
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Elasticsearch
          elasticsearch:
            annotations:
              openshift.io/node-selector: "node-role.kubernetes.io/servicemesh-elasticsearch="
            nodeCount: 3
            storage: 
              storageClassName: ocs-storagecluster-cephfs
              size: 100Gi
            resources:
              requests:
                cpu: 200m
                memory: 8Gi
              limits:
                memory: 16Gi
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  profiles:
    - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger