resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
- grafana-instance.yaml
- grafana-monitoring-sa.yaml
- grafana-token-secret.yaml
- grafana-datasource.yaml
- grafana-dashboard.yaml
- route.yaml
- monitoring/kube-state-metrics.yaml
- monitoring/prometheus.yaml
- monitoring/prometheus-config.yaml
- monitoring/prometheus-rbac.yaml
- monitoring/pushgateway.yaml
