apiVersion: v1
kind: Secret
metadata:
  name: dso-quay-user
  annotations:
    tekton.dev/docker-0: https://dso-quay-registry-quay-quay-enterprise.apps.ocp1.azure.dso.digital.mod.uk # Described below for quay
type: kubernetes.io/basic-auth
stringData:
  username: <quay-username>
  password: <quay-password>