apiVersion: v1
kind: Namespace
metadata:
  name: dso-bookinfo
  labels:
    argocd.argoproj.io/managed-by: "bookinfoargocd"
  annotations:
    openshift.io/display-name: 'dso-bookinfo'
    openshift.io/description: "hosts bookinfo"
