apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-credentials
  namespace: sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sample-app-credentials
  data:
  - secretKey: greeting
    remoteRef:
      key: sample-app
      property: greeting
