kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-settings1
  namespace: dev-kafka-edaapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi