apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s: 
      retention: 7d
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      resources:       
        limits:
          cpu: 4
          memory: 8Gi
        requests:
          cpu: 2
          memory: 2Gi
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 20Gi  
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 10Gi
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"    
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    grafana:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ''    
      tolerations:
      - key: "node.workload.openshift.io/infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"