apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams-operator
  namespace: amq-streams
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: "stable"
  installPlanApproval: Manual
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace