{
 "title": "Litmus / ChaosCenter / Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chaosresult_name",
    "label": "Chaos Result",
    "query": {
     "query": "label_values(litmuschaos_awaited_experiments{job=~\"chaos-exporter\"}, chaosresult_name)"
    }
   },
   {
    "name": "chaosengine_context",
    "label": "Chaos Engine context",
    "query": {
     "query": "label_values(litmuschaos_experiment_verdict{job=~\"chaos-exporter\"}, chaosengine_context)"
    }
   },
   {
    "name": "namespace",
    "label": "ChaosCenter namespace",
    "query": {
     "query": "label_values(litmuschaos_experiment_verdict, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Chaos Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chaos Annotations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Chaos events and metrics" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Chaos Experiments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Chaos injections" }
   ],
   "targets": [
    {
     "expr": "litmuschaos_awaited_experiments{job=\"chaos-exporter\"}",
     "legendFormat": "{{chaosresult_name}}"
    }
   ]
  },
  {
   "title": "Total Experiments Run",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments{job=\"chaos-exporter\"} + litmuschaos_failed_experiments{job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Passed Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments{job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Failed Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_failed_experiments{job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Queued Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_awaited_experiments{job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Chaos Experiment Verdict Failure Alerts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Experiments failed" }
   ],
   "targets": [
    {
     "expr": "litmuschaos_experiment_verdict{job=\"chaos-exporter\", chaosresult_verdict=\"Fail\"}",
     "legendFormat": "{{app_label}} - {{chaosresult_name}} - {{chaosresult_verdict}}"
    }
   ]
  },
  {
   "title": "Chaos Experiment Probe Failure Alerts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Probes failed" }
   ],
   "targets": [
    {
     "expr": "litmuschaos_experiment_verdict{job=\"chaos-exporter\", probe_success_percentage!=\"100.000000\"}",
     "legendFormat": "{{app_label}} - {{chaosresult_name}} - {{probe_success_percentage}}"
    }
   ]
  },
  { "title": "Compute resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pod - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod!=\"\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  },
  {
   "title": "Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container!=\"POD\",pod!=\"\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}