kind: ServiceAccount
apiVersion: v1
metadata:
  name: openshift-backup
  namespace: ocp-etcd-backup
  labels:
    app: openshift-backup
  annotations:
    argocd.argoproj.io/sync-wave: "2"
secrets:
  - name: artifactory-image-pull
imagePullSecrets:
  - name: artifactory-image-pull