apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: devel
    version: v0.8.0
  name: chains-config
  namespace: openshift-pipelines
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: kms
  artifacts.oci.storage: tekton,oci
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.signer: kms
  artifacts.taskrun.storage: tekton,oci
  signers.kms.auth.address: 'https://vault.apps.management.balancing.nationalgrideso.com'
  signers.kms.auth.token: 'hvs.CAESILjVGQgHH4VQOwzp-mQVk5wPDDAaIUHfwZkxqRgKrHoAGiMKHGh2cy5sTG9hQVFtOEZQcHVsNTRlU1BDdHpzczUQ5dieAQ'
  signers.kms.kmsref: 'hashivault://development-signing-key'