apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres.keycloak.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: POSTGRES_USERNAME
    passwordSecret:
      name: keycloak-db-secret
      key: POSTGRES_PASSWORD
  http:
    httpEnabled: true
  proxy:
    headers: xforwarded
  hostname:
    hostname: keycloak-keycloak.apps-crc.testing
    strict: false
    strictBackchannel: false
