apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: rgb-admin-user
  labels:
    app: keycloak
  namespace: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  user:
    username: rgb-admin
    enabled: true
    email: admin@rgb.com
    firstName: RGB
    lastName: Admin
    credentials:
      - type: password
        value: password123
    realmRoles:
      - admin
