apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: rgb-realm
  labels:
    app: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      app: keycloak
  realm:
    id: rgb-realm
    realm: rgb-realm
    enabled: true
    displayName: RGB Realm
