apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: computab0y-user
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  user:
    username: computab0y
    enabled: true
    email: computab0y@rgb.com
    firstName: Computab0y
    credentials:
      - type: password
        value: qwerty
    realmRoles:
      - admin
