apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  keycloakDeploymentSpec:
    template:
      spec:
        containers:
          - name: keycloak
            readinessProbe:
              failureThreshold: 30
              initialDelaySeconds: 300
              periodSeconds: 30
              timeoutSeconds: 15
