kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pipeline-validation-route
  namespace: dev-int
spec:
  host: validation-bitbucket-listener-dev-int.apps.devops.balancing.nationalgrideso.com
  to:
    kind: Service
    name: el-pipeline-validation-event-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
