apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: my-app-secret-from-vault
  data:
  - secretKey: username
    remoteRef:
      key: my-app-secret
      property: username
  - secretKey: password
    remoteRef:
      key: my-app-secret
      property: password
