resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
- vault-token-secret.yaml
- clustersecretstore.yaml
- example-externalsecret.yaml
- example-certificate.yaml
- externalsecretsconfig.yaml
- networkpolicy.yaml
