apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: istio-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  channel: "stable"
  installPlanApproval: Manual
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: servicemeshoperator.v2.3.3