apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: edb-postgresql-recovery
  namespace: edb-postgresql-recovery
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    categories: database
  labels:
    environment: edb-recovery
    workload: database
spec:
  description: "EDB Recovery Cluster"
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised
  logLevel: info
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  
  # superuserSecret:
  #   name: edb-postgresql-recovery-superuser
  storage:          
    size: 100Gi      
    storageClass: ocs-storagecluster-ceph-rbd
  bootstrap:
    recovery:
      source: edb-postgresql-dev-pr-1

  externalClusters:
    - name: edb-postgresql-dev-pr-1
      barmanObjectStore:
        destinationPath: "https://esodevuksedbbackup.blob.core.windows.net/edbbackup"
        azureCredentials:
          connectionString:
            name: azure-creds
            key: AZURE_STORAGE_CONNECTION_STRING
        wal:
          maxParallel: 8