apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops # it got deployed on openshift-operators
  annotations:
    openshift.io/node-selector: "node-role.kubernetes.io/worker="  
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node.workload.openshift.io/worker", "Operator": "Equal", "Value": "true", "Effect": "NoSchedule"}]'