### This rbac used to enable prometheus to pull metrics
### from this namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus-read
  namespace: litmus
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-prometheus-k8s-read-binding
  namespace: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-read
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring