apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ftp-credentials
  namespace: openshift-pipelines-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ftp-credentials
  data:
  - secretKey: username
    remoteRef:
      key: ftp-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: ftp-credentials
      property: password
