apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ftp-file-pipeline
  namespace: openshift-pipelines-operator
  annotations:
    style.tekton.dev/descriptors: |
      - path: params.username
        displayName: Username
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select
        - urn:alm:descriptor:com.tectonic.ui:label:list
        - urn:alm:descriptor:com.tectonic.ui:value:list
      - path: params.action
        displayName: Action
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select
        - urn:alm:descriptor:com.tectonic.ui:label:list-files
        - urn:alm:descriptor:com.tectonic.ui:value:list-files
        - urn:alm:descriptor:com.tectonic.ui:label:create-file
        - urn:alm:descriptor:com.tectonic.ui:value:create-file
        - urn:alm:descriptor:com.tectonic.ui:label:delete-file
        - urn:alm:descriptor:com.tectonic.ui:value:delete-file
      - path: params.target-folder
        displayName: Target Folder
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select
        - urn:alm:descriptor:com.tectonic.ui:label:SUBMISSION
        - urn:alm:descriptor:com.tectonic.ui:value:SUBMISSION
        - urn:alm:descriptor:com.tectonic.ui:label:NOTIFICATION
        - urn:alm:descriptor:com.tectonic.ui:value:NOTIFICATION
        - urn:alm:descriptor:com.tectonic.ui:label:BOTH
        - urn:alm:descriptor:com.tectonic.ui:value:BOTH
spec:
  params:
  - name: username
    type: string
    description: "FTP user (populated from Vault after keycloak-vault-sync runs)"
    default: "list"
  - name: action
    type: string
    description: "Action to perform on the FTP server"
    default: "list-files"
  - name: target-folder
    type: string
    description: "Target folder on the FTP server"
    default: "SUBMISSION"
  - name: file-name
    type: string
    description: "Name of the file to create or delete (required for create-file and delete-file)"
    default: ""
  - name: vault-address
    type: string
    description: "The address of the Vault server"
    default: "http://vault.vault.svc:8200"
  tasks:
  - name: ftp-operation
    taskRef:
      name: keycloak-vault-sync
    params:
    - name: ftp-host
      value: "10.211.55.4"
    - name: ftp-port
      value: "21"
    - name: username
      value: $(params.username)
    - name: action
      value: $(params.action)
    - name: target-folder
      value: $(params.target-folder)
    - name: file-name
      value: $(params.file-name)
    - name: vault-address
      value: $(params.vault-address)
    - name: target-ou
      value: "FTP-Users"
