apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ftp-sync-parallels-run-
  namespace: openshift-pipelines-operator
spec:
  pipelineRef:
    name: ftp-sync-pipeline
  params:
  - name: ftp-host
    value: "10.211.55.4"
  - name: ftp-port
    value: "21"
  - name: username
    value: "testuser"
  - name: action
    value: "list-files"
  - name: target-folder
    value: "NOTIFICATION"
  - name: file-name
    value: "test-from-parallels.txt"
