apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ftp-sync-external-run-
  namespace: openshift-pipelines-operator
spec:
  pipelineRef:
    name: ftp-file-pipeline
  params:
  - name: ftp-host
    value: "mock-ftp-service.test-app.svc.cluster.local"
  - name: ftp-port
    value: "2121"
  - name: username
    value: "testuser"
  - name: action
    value: "list-files"
  - name: target-folder
    value: "NOTIFICATION"
  - name: file-name
    value: "test-from-external.txt"
