apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ftp-sync-pipeline
  namespace: openshift-pipelines-operator
spec:
  params:
  - name: ftp-host
    type: string
    description: "The external FTP server host"
  - name: ftp-port
    type: string
    description: "The external FTP server port"
    default: "21"
  - name: username
    type: string
    description: "The FTP username to connect as (or 'list' to list available accounts)"
    default: "testuser"
    enum:
    - "list"
    - "testuser"
    - "testuser2"
    - "testuser3"
  - name: action
    type: string
    description: "Action to perform: list-files, create-file, delete-file"
    default: "list-files"
    enum:
    - "list-files"
    - "create-file"
    - "delete-file"
  - name: target-folder
    type: string
    description: "The folder to create or delete file in (SUBMISSION or NOTIFICATION)"
    default: "NOTIFICATION"
    enum:
    - "SUBMISSION"
    - "NOTIFICATION"
  - name: file-name
    type: string
    description: "The name of the file to create or delete"
    default: ""
  - name: vault-address
    type: string
    description: "The address of the Vault server"
    default: "http://vault.vault.svc:8200"
  tasks:
  - name: run-ftp-operation
    taskRef:
      name: ftp-operation
    params:
    - name: ftp-host
      value: $(params.ftp-host)
    - name: ftp-port
      value: $(params.ftp-port)
    - name: username
      value: $(params.username)
    - name: action
      value: $(params.action)
    - name: target-folder
      value: $(params.target-folder)
    - name: file-name
      value: $(params.file-name)
    - name: vault-address
      value: $(params.vault-address)
