apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: keycloak-vault-sync-run-
  namespace: openshift-pipelines-operator
spec:
  pipelineRef:
    name: keycloak-vault-sync
  params:
  - name: target-ou
    value: "FTP-Users"
