apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: keycloak-vault-sync
  namespace: openshift-pipelines-operator
spec:
  tasks:
  - name: sync-users
    taskRef:
      name: keycloak-vault-sync
    params:
    - name: username
      value: "list"
    - name: action
      value: "sync-users"
