apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ftp-sync-pipeline-run-
  namespace: openshift-pipelines-operator
spec:
  pipelineRef:
    name: ftp-sync-pipeline
  params:
  - name: ftp-host
    value: "127.0.0.1"
  - name: ftp-port
    value: "2121"
  - name: submission-folder
    value: "SUBMISSION"
  - name: notification-folder
    value: "NOTIFICATION"
  - name: create-test-file
    value: "true"
