apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  nodeTopologies: {}
  storageDeviceSets:
  - config: {}
    count: 1 # +1 to increase storage by 2TB...adds more disks (vertical scaling)...max 3 and then need to add more storage nodes
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2048Gi
        storageClassName: managed-premium
        volumeMode: Block
      status: {}
    name: ocs-deviceset-managed-premium
    placement: {}
    portable: true
    preparePlacement: {}
    replica: 3
    resources: {}
  version: 4.8.0