kind: Secret
apiVersion: v1
metadata:
  name: openid-client-secret-azuread
  namespace: openshift-config
data:
  clientSecret: <Azure Service Principal in Base64> # echo "ServicePrincipal" | base64
type: Opaque