apiVersion: v1
kind: Secret
metadata:
  name: pipeline-env
  namespace: openshift-pipelines-operator
type: Opaque
stringData:
  keycloak-admin-username: "REPLACE_ME"   # Keycloak admin username
  keycloak-admin-password: "REPLACE_ME"   # Keycloak admin password
