apiVersion: v1
kind: Namespace
metadata:
  name: group-sync-operator
  annotations:
    openshift.io/node-selector: "node-role.kubernetes.io/worker="  
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node.workload.openshift.io/worker", "Operator": "Equal", "Value": "true", "Effect": "NoSchedule"}]'    
    argocd.argoproj.io/sync-wave: "1"
  labels:
    openshift.io/cluster-monitoring: "true"
