apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: group-sync-operator-group
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - group-sync-operator
