kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        volumeMounts:
        - mountPath: /var/lib/postgresql/
          subPath: data
          name: postgres-pv-lts
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
      volumes:
      - name: postgres-pv-lts
        persistentVolumeClaim:
          claimName: postgres-pv-lts