kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-lts
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem