apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data-lts
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 10Gi
