apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: devops-nfk2l
    machine.openshift.io/cluster-api-machine-role: worker-cni-qz
    machine.openshift.io/cluster-api-machine-type: worker
  name: worker-cni-qz-zone3
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: devops-nfk2l
      machine.openshift.io/cluster-api-machineset: worker-cni-qz-zone3
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: devops-nfk2l
        machine.openshift.io/cluster-api-machine-role: worker-cni-qz
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: worker-cni-qz-zone3
    spec:
      taints:
        - effect: NoSchedule
          key: node-role.kubernetes.io/worker-cni-qz
          value: "true"
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/worker-cni-qz: ""
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/eso-dev-uks-devops-rg/providers/Microsoft.Compute/images/devops-nfk2l
            sku: ""
            version: ""
          internalLoadBalancer: ""          
          kind: AzureMachineProviderSpec
          location: uksouth
          managedIdentity: devops-nfk2l-identity
          networkResourceGroup: 5690-dev-uks-spokenetwork-rg
          osDisk:
            diskSizeGB: 160     # See Confluence - change later
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          resourceGroup: eso-dev-uks-devops-rg     # from Azure
          subnet: lz5690-DEV-uks-worker-snet-01         # from Azure
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D8s_v4
          vnet: 5690-dev-uks-vnet-02
          zone: "3"