apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-git-credentials
  namespace: sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sample-app-git-credentials
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      data:
        username: "{{ .username }}"
        password: "{{ .token }}"
  data:
  - secretKey: username
    remoteRef:
      key: sample-app-pipeline
      property: github-username
  - secretKey: token
    remoteRef:
      key: sample-app-pipeline
      property: github-token
