apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bookinfoargocd-namespace.yaml
  - bookinfoargocd-argocr.yaml
  - bookinfoargocd-doer-sa.yaml
  - bookinfoargocd-doer-clusterrole.yaml
