resources:
- namespace.yaml
- operator-group.yaml
- subscription.yaml
- health-check/task.yaml
- health-check/pipeline.yaml
- health-check/cronjob.yaml
- health-check/serviceaccount.yaml
- ftp-pipeline/externalsecret.yaml
- ftp-pipeline/vault-token.yaml
- ftp-pipeline/task.yaml
- ftp-pipeline/pipeline.yaml
- ftp-pipeline/ftp-vm-ssh-key.yaml
