apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backup
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://bitbucket.uk.ngridtools.com/scm/efe/devops-cluster-config.git
    targetRevision: master
    path: gitops/backup/
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true