apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-subscription
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argocd-appsets/operators/subscription
    repoURL: https://bitbucket.uk.ngridtools.com/scm/efe/devops-cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true