apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-namespace-dev-int
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/dev-int-namespace
    repoURL: https://bitbucket.uk.ngridtools.com/scm/efe/env-dev-int.git
    targetRevision: master
  syncPolicy:
    automated:
    prune: true
    selfHeal: true