# FROM-SCRATCH REBUILD of the Contabo OKD single-node cluster - DESTRUCTIVE.
#
# This is deliberately a separate root module from ../contabo-okd (which is the safe,
# day-to-day "manage the running instance" config and never reinstalls anything).
#
# Applying this module REINSTALLS instance var.existing_instance_id with a plain Debian
# image and your SSH key. Everything on the disk - the running OKD cluster, Keycloak,
# Vault, all PVs - is wiped. The IP address is kept (reinstall, not a new instance).
#
# Afterwards, ansible/contabo-okd-install turns that Debian box into an OKD SNO node
# (kexec into the SCOS live image, bootstrap-in-place install to disk), then
# ansible/contabo-okd re-applies all day-2 config. scripts/rebuild-contabo-okd.sh runs
# all three steps in order.

# Public key for the node. The same key is used for root@Debian (this stage) and for
# core@SCOS (baked into install-config by the install playbook).
resource "contabo_secret" "okd_ssh_key" {
  name  = "okd-${var.cluster_name}-ssh"
  type  = "ssh"
  value = trimspace(file(pathexpand("${var.ssh_private_key_path}.pub")))
}

resource "contabo_instance" "okd_node" {
  existing_instance_id = var.existing_instance_id
  display_name         = var.display_name
  product_id           = var.product_id
  region               = var.region

  # Changing either of these reinstalls the instance - that is the point of this module.
  image_id     = var.debian_image_id
  ssh_keys     = [tonumber(contabo_secret.okd_ssh_key.id)]
  default_user = "root"

  lifecycle {
    precondition {
      condition     = var.confirm_wipe_instance_id == var.existing_instance_id
      error_message = "Refusing to reinstall: set confirm_wipe_instance_id to the instance ID (${var.existing_instance_id}) to confirm you want to WIPE it."
    }
  }
}

resource "cloudflare_dns_record" "api" {
  zone_id = var.cloudflare_zone_id
  name    = "api.${var.cluster_name}.${var.base_domain}"
  type    = "A"
  content = var.instance_ipv4
  ttl     = 300
  proxied = false
  comment = "OKD API - managed by terraform/contabo-okd-rebuild"
}

resource "cloudflare_dns_record" "apps_wildcard" {
  zone_id = var.cloudflare_zone_id
  name    = "*.apps.${var.cluster_name}.${var.base_domain}"
  type    = "A"
  content = var.instance_ipv4
  ttl     = 300
  proxied = false
  comment = "OKD apps wildcard - managed by terraform/contabo-okd-rebuild"
}

# Hand-off to the install playbook: inventory pointing at the freshly reinstalled Debian.
resource "local_file" "install_inventory" {
  filename        = "${path.module}/../../ansible/contabo-okd-install/inventory.ini"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by terraform/contabo-okd-rebuild - do not edit by hand.
    [installer_host]
    okd-node ansible_host=${var.instance_ipv4} ansible_user=root ansible_ssh_private_key_file=${var.ssh_private_key_path}

    [installer_host:vars]
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  EOT
  depends_on      = [contabo_instance.okd_node]
}
