apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Manual
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
